# Generated by Django 5.0.1 on 2024-01-26 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=datetime.datetime(2024, 1, 26, 6, 43, 14, 913802, tzinfo=datetime.timezone.utc), upload_to='media'),
            preserve_default=False,
        ),
    ]
